### ISSUE TITLE
Translation PTBR archive

### ISSUE THREAD

**Issue by helens0uza** [NermNermNerm/StardewMods#2]
Heey!
I tried uploading to Nexus but it didn't work. So here u go. If there's anything that need correction or something like that let me know.

Thank you so much again for this amazing mod!

[pt.json](https://github.com/user-attachments/files/16283215/pt.json)

*PS: Sorry for not doing Ingestion/Internalization thing, I don't understand anything about coding and I have zero skills in it.

**Comment by NermNermNerm** [comment]
Shipped it!
